

services:
  backend:
    build: ./backend
    container_name: theorex_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: theorex_frontend
    ports:
      - "3000:80"
